project:
  type: website
  preview:
   watch-inputs: false

website:

  # announcement:
  #   icon: exclamation-triangle
  #   dismissable: false
  #   content: "**Warning** - The course website is still under construction. All information is not definitive yet, and may change without warning."
  #   type: warning
  #   position: above-navbar

  page-navigation: true
  title: "8BM050"
  description: "Homepage for 8BM050 - Systems Biology Models at Eindhoven University of Technology"

  open-graph: true

  repo-url: https://github.com/8BM050/24-25
  repo-actions: [edit, issue]

  page-footer:
    left: "The webpage was built with ❤️ and [Quarto](https://quarto.org/)."
    right:
    - text: Attributions
      href: ATTRIBUTIONS.md
    center: "Academic year 2024-2025"

  navbar:
    background: "#C81919"
    logo: "assets/course-logo-small.png"
    title: "Systems Biology Models"
    collapse-below: lg

    right:
      - icon: github
        href: https://github.com/8BM050/24-25
        aria-label: GitHub

  sidebar:
  # Main page sidebar
    - id: index
      title: "Lectures"
      style: "docked"
      collapse-level: 1
      alignment: "left"
      background: light
      contents:
      - text: "Home"
        href: index.qmd
      - section: "Lectures"
        contents:
        - text: "Week 1"
        - text: "---"
        - href: lectures/1a-course-introduction.qmd
        - href: lectures/1b-graph-theory.qmd
        - text: "Week 2"
        - text: "---"
        - href: lectures/2a-differential-equations.qmd
        - href: lectures/2b-cell-biology.qmd
        - text: "Week 3"
        - text: "---"
        - href: lectures/3a-biological-models.qmd
        - href: lectures/3b-digestive-system.qmd
        - text: "Week 4"
        - text: "---"
        - href: lectures/4a-building-models.qmd
        - href: lectures/4b-organ-specialization.qmd
        - text: "Week 5"
        - text: "---"
        - href: lectures/5a-metabolism-in-daily-life.qmd
        - href: lectures/5b-exercise-and-extreme-situations.qmd
        - text: "Week 6"
        - text: "---"
        - href: lectures/6a-endocrinology.qmd
        - href: lectures/6b-immunometabolism.qmd
        - text: "Week 7"
        - text: "---"
        - href: lectures/7a-diabetes.qmd
        # - href: lectures/7b-clinical-endocrinology.qmd
      - section: "Practicals"
        contents:
        - href: 8bm050/environment-setup/environment.qmd
        - text: "ODEs with Python I"
          href: 8bm050/notebooks/01-ode-simulation-with-Python.ipynb
        - text: "ODEs with Python II"
          href: 8bm050/notebooks/02-whole-body-models.ipynb

    # Staff page sidebar
    - id: staff
      title: "Staff"
      contents:
        - section: "Lecturers"
          contents: "staff/lecturers/*.qmd"
        - section: "Teaching Assistants"
          contents: "staff/assistants/*.qmd"

# Formatting options
format:
  html:
    theme: 
      light: [yeti, style/theme.scss]
      dark: [yeti, style/theme.scss, style/theme-dark.scss]
    mainfont: "Avenir Next"
    toc: true