---
title: "8BM050 - Systems Biology Models"
engine: julia
toc: true
page-layout: full
execute:
  echo: false

listing:
  # Lectures
  - id: lectures
    contents: 
      - lectures
    type: table
    categories: false
    fields: [date, time, title]
    sort: date
    date-format: "ddd, D MMM"
    field-display-names:
      date: "**Date**"
      title: "**Title**" 
      author: "Lecturer"
      categories: "Category"
      time: "Time"
  
  # Assignments & Quizzes
  - id: assignments
    contents:
      - assignments.yml
    type: table
    table-striped: true
    table-hover: true
    fields: [title, categories, date]
    sort: date
    date-format: "ddd, D MMM HH:mm"
    field-display-names:
      title: "**Description**" 
      categories: "**Type**"
      date: "**Deadline**"
  
  # Staff - Lecturers
  - id: lecturers
    contents: "staff/lecturers/*.qmd"
    type: grid
    image-height: 225px
    grid-columns: 4
    fields: [image, title, subtitle]
    grid-item-align: center
    sort: sortby
  # Staff - Teaching Assistants
  - id: teaching-assistants
    contents: "staff/assistants/*.qmd"
    type: grid
    image-height: 225px
    grid-columns: 4
    sort: sortby
    fields: [image, title, subtitle]
    field-display-names: 
      started: "Started"
    grid-item-align: center
---

::: {.callout-caution title="Information regarding the postponement of the course"}
Due to the cyber attack at the Eindhoven University of Technology, the start of the course has been postponed by **one week**. The course will now start on February 12, 2025. The course schedule has been adjusted accordingly. Additionally, the following changes have been made to the course schedule:

  - Lecture 7A - endocrinology, is now in the sixth week of lectures, in place of lecture 6A - immunometabolism
  - Lecture 6A - immunometabolism, is now on Friday of the sixth week, in place of lecture 6B - diabetes
  - Lecture 6B - diabetes, is now in the seventh week of lectures, in place of lecture 7A - endocrinology
  - Lecture 7B - clinical endocrinology is **cancelled** and will not be rescheduled. 

  You will find the updated schedule on the website.
:::

```{julia}
# | output: false
using Pkg
Pkg.instantiate()
```

::: {.callout-note title="Welcome to the 8BM050 course!"}
```{julia}
# This Julia code generates a welcome message based on the current date

using Dates
using Markdown
using YAML

# Generate welcome message
function welcome(weeknumber::Int, page_1::String, page_1_link::String, page_2::String, page_2_link::String)
  return "Welcome to **week $(weeknumber)** of the 8BM050 course!\n\n- Lecture A: [$(page_1)]($(page_1_link))\n\n- Lecture B: [$(page_2)]($(page_2_link))"
end

function welcome(weeknumber::Int, page_1::String, page_1_link::String)
  return "Welcome to **week $(weeknumber)** of the 8BM050 course!\n\n- Lecture A: [$(page_1)]($(page_1_link))\n\n- Lecture B: -"
end

# Set up the notification dates and corresponding welcome messages
notification_dates = Dict(
  DateTime(2025, 1, 1) => welcome(
    1, "Course Introduction", "lectures/1a-course-introduction.qmd",
    "Graph Theory", "lectures/1b-graph-theory.qmd"),
  DateTime(2025, 2, 17) => welcome(
    2, "Dynamic Models", "lectures/2a-differential-equations.qmd",
    "Cell Biology of Metabolism", "lectures/2b-cell-biology.qmd"),
  DateTime(2025, 2, 24) => welcome(
    3, "Biological Models", "lectures/3a-biological-models.qmd",
    "Digestive System", "lectures/3b-digestive-system.qmd"),
  DateTime(2025, 3, 10) => welcome(
    4, "Building Models", "lectures/4a-building-models.qmd",
    "Organ Specialization", "lectures/4b-organ-specialization.qmd"),
  DateTime(2025, 3, 17) => welcome(
    5, "Metabolism in Daily Life", "lectures/5a-metabolism-in-daily-life.qmd",
    "Metabolism in Exercise and Extreme Situations", "lectures/5b-exercise-and-extreme-situations.qmd"),
  DateTime(2025, 3, 24) => welcome(
    6, "Endocrinology", "lectures/6a-endocrinology.qmd",
    "Immunometabolism", "lectures/6b-immunometabolism.qmd"),
  DateTime(2025, 3, 31) => welcome(
    7, "Diabetes", "lectures/7a-diabetes.qmd"),
)

notification_index = findlast(x -> x <= today(), sort(collect(keys(notification_dates))))

assignments = YAML.load_file("assignments.yml")
format = DateFormat("mm-dd-yyyy HH:MM")
deadlines = DateTime.([assignment["date"] for assignment in assignments], format)
titles = [assignment["title"] for assignment in assignments]
links = [assignment["path"] for assignment in assignments]

function deadline_message(deadlines::Vector{DateTime}, titles::Vector{String})
  today_date = today()
  upcoming_deadlines = filter(x -> week(x) == week(today_date), deadlines)
  upcoming_titles = titles[findall(x -> week(x) == week(today_date), deadlines)]
  upcoming_links = links[findall(x -> week(x) == week(today_date), deadlines)]

  if isempty(upcoming_deadlines)
    return "There are no upcoming deadlines this week."
  else
    message = "Deadlines this week:\n"
    for (i, deadline) in enumerate(upcoming_deadlines)
      message *= "- [$(upcoming_titles[i])]($(upcoming_links[i])) on $(Dates.format(deadline, "d U, yyyy"))\n"
    end
    return message
  end
end


if isnothing(notification_index)
  notification = md"Welcome to the 8BM050 course! The course has not yet started."
else
  notification = Markdown.parse(notification_dates[sort(collect(keys(notification_dates)))[notification_index]]*"\n\n"*
    deadline_message(deadlines, titles))
end

notification
```
:::

[<svg fill="#FFFFFF" width="14" height="14" viewBox="0 0 1920 1920" xmlns="http://www.w3.org/2000/svg">
    <path d="M958.568 277.97C1100.42 277.97 1216.48 171.94 1233.67 34.3881 1146.27 12.8955 1054.57 0 958.568 0 864.001 0 770.867 12.8955 683.464 34.3881 700.658 171.94 816.718 277.97 958.568 277.97ZM35.8207 682.031C173.373 699.225 279.403 815.285 279.403 957.136 279.403 1098.99 173.373 1215.05 35.8207 1232.24 12.8953 1144.84 1.43262 1051.7 1.43262 957.136 1.43262 862.569 12.8953 769.434 35.8207 682.031ZM528.713 957.142C528.713 1005.41 489.581 1044.55 441.31 1044.55 393.038 1044.55 353.907 1005.41 353.907 957.142 353.907 908.871 393.038 869.74 441.31 869.74 489.581 869.74 528.713 908.871 528.713 957.142ZM1642.03 957.136C1642.03 1098.99 1748.06 1215.05 1885.61 1232.24 1908.54 1144.84 1920 1051.7 1920 957.136 1920 862.569 1908.54 769.434 1885.61 682.031 1748.06 699.225 1642.03 815.285 1642.03 957.136ZM1567.51 957.142C1567.51 1005.41 1528.38 1044.55 1480.11 1044.55 1431.84 1044.55 1392.71 1005.41 1392.71 957.142 1392.71 908.871 1431.84 869.74 1480.11 869.74 1528.38 869.74 1567.51 908.871 1567.51 957.142ZM958.568 1640.6C816.718 1640.6 700.658 1746.63 683.464 1884.18 770.867 1907.11 864.001 1918.57 958.568 1918.57 1053.14 1918.57 1146.27 1907.11 1233.67 1884.18 1216.48 1746.63 1100.42 1640.6 958.568 1640.6ZM1045.98 1480.11C1045.98 1528.38 1006.85 1567.51 958.575 1567.51 910.304 1567.51 871.172 1528.38 871.172 1480.11 871.172 1431.84 910.304 1392.71 958.575 1392.71 1006.85 1392.71 1045.98 1431.84 1045.98 1480.11ZM1045.98 439.877C1045.98 488.148 1006.85 527.28 958.575 527.28 910.304 527.28 871.172 488.148 871.172 439.877 871.172 391.606 910.304 352.474 958.575 352.474 1006.85 352.474 1045.98 391.606 1045.98 439.877ZM1441.44 1439.99C1341.15 1540.29 1333.98 1697.91 1418.52 1806.8 1579 1712.23 1713.68 1577.55 1806.82 1418.5 1699.35 1332.53 1541.74 1339.7 1441.44 1439.99ZM1414.21 1325.37C1414.21 1373.64 1375.08 1412.77 1326.8 1412.77 1278.53 1412.77 1239.4 1373.64 1239.4 1325.37 1239.4 1277.1 1278.53 1237.97 1326.8 1237.97 1375.08 1237.97 1414.21 1277.1 1414.21 1325.37ZM478.577 477.145C578.875 376.846 586.039 219.234 501.502 110.339 341.024 204.906 206.338 339.592 113.203 498.637 220.666 584.607 378.278 576.01 478.577 477.145ZM679.155 590.32C679.155 638.591 640.024 677.723 591.752 677.723 543.481 677.723 504.349 638.591 504.349 590.32 504.349 542.048 543.481 502.917 591.752 502.917 640.024 502.917 679.155 542.048 679.155 590.32ZM1440 475.712C1540.3 576.01 1697.91 583.174 1806.8 498.637 1712.24 338.159 1577.55 203.473 1418.51 110.339 1332.54 217.801 1341.13 375.413 1440 475.712ZM1414.21 590.32C1414.21 638.591 1375.08 677.723 1326.8 677.723 1278.53 677.723 1239.4 638.591 1239.4 590.32 1239.4 542.048 1278.53 502.917 1326.8 502.917 1375.08 502.917 1414.21 542.048 1414.21 590.32ZM477.145 1438.58C376.846 1338.28 219.234 1331.12 110.339 1415.65 204.906 1576.13 339.593 1710.82 498.637 1805.39 584.607 1696.49 577.443 1538.88 477.145 1438.58ZM679.155 1325.37C679.155 1373.64 640.024 1412.77 591.752 1412.77 543.481 1412.77 504.349 1373.64 504.349 1325.37 504.349 1277.1 543.481 1237.97 591.752 1237.97 640.024 1237.97 679.155 1277.1 679.155 1325.37Z"/> </svg> Canvas →]({{< var canvas >}}){.btn .btn-danger role="button" data-toggle="tooltip" title="Canvas Page"}
[<svg fill="#FFFFFF" width="14" height="14" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd"><path d="M22 24h-17c-1.657 0-3-1.343-3-3v-18c0-1.657 1.343-3 3-3h17v24zm-2-4h-14.505c-1.375 0-1.375 2 0 2h14.505v-2zm0-18h-15v16h15v-16zm-3 3v3h-9v-3h9z"/></svg> Lecture Notes →](https://github.com/8BM050/lecture-notes/releases/latest/download/main.pdf){.btn .btn-success .mr-4 }
[<svg fill="#FFFFFF" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
	 width="14" height="14" viewBox="0 0 416.979 416.979"
	 xml:space="preserve">
<g>
	<path d="M356.004,61.156c-81.37-81.47-213.377-81.551-294.848-0.182c-81.47,81.371-81.552,213.379-0.181,294.85
		c81.369,81.47,213.378,81.551,294.849,0.181C437.293,274.636,437.375,142.626,356.004,61.156z M237.6,340.786
		c0,3.217-2.607,5.822-5.822,5.822h-46.576c-3.215,0-5.822-2.605-5.822-5.822V167.885c0-3.217,2.607-5.822,5.822-5.822h46.576
		c3.215,0,5.822,2.604,5.822,5.822V340.786z M208.49,137.901c-18.618,0-33.766-15.146-33.766-33.765
		c0-18.617,15.147-33.766,33.766-33.766c18.619,0,33.766,15.148,33.766,33.766C242.256,122.755,227.107,137.901,208.49,137.901z"/>
</g>
</svg> Course Information →](info/info.qmd){.btn .btn-other .mr-4 }

This course will discuss principles of human metabolism and its regulation. Basic principles will be discussed first, such as the central human energy metabolism and regulation of metabolism at a cellular level. Then, the functional anatomy of digestive tract, metabolism and its regulatory organs are discussed, additionally discussing regulatory hormones. Finally, the knowledge will be integrated into the discussion of whole-body metabolism, and its adaptation to factors such as stress, exercise and disease. 

The biological theory will be complemented by an engineering perspective on metabolic regulation, by discussion of techniques to statically and dynamically model components of this regulatory system. We will discuss the basics of mathematical graph theory and use these to move from static models to dynamic models of biochemical processes and signalling networks. During the practical part of the course, students will be working with these models and using Python to perform simulations and analyses.

## 🏁 Learning Outcomes
At the end of this course, the student is able to:

1.  Describe the molecular details of the conversion of the body's main energy sources (carbohydrates, lipids, proteins) into energy.
2.  Understand and describe the compartmentalisation and adaptation of metabolic processes at a cellular level.
3.  Understand and describe the functional anatomy of the digestive system for carbohydrates, lipids and proteins.
4.  Describe the function of the liver, adipose tissue, and other metabolic tissues in retaining homeostasis through hormonal and neural regulation
5.  Describe energy homeostasis in daily life and how it changes due to stress, exercise, and disease
6.  Apply concepts of graph theory (connectivity, directionality, cycles, and self-loops) to study metabolic processes and regulation
7.  Construct a linear dynamic model of biochemical processes using the law of mass action
8.  Explain the function of different terms in a simple system of (possibly nonlinear) ordinary differential equations.
9.  Calculate the steady-state conditions for a simple system of ordinary differential equations.
10. Use Python to simulate and analyse systems of ordinary differential equations

## 📅 Lecture Schedule
Below you can find the scheduled lectures. You can also use the navigation bar on the left to navigate to various lecture pages. Please use [TimeEdit](https://cloud.timeedit.net/nl_tue/web/?en=t) to find the location of each lecture.

:::{#lectures}
:::

## 📝 Assessment & Deadlines
:::{#assignments}
:::
<!-- The assessments for this course have been scheduled per week, and can be found in the following table.

|                | Week 1  | Week 2 | Week 3 | Week 4 | Week 5 | Week 6 | Week 7 | Week 8 | Examination period | 
|----------------|---------| ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------------------ | 
| [Weekly quizzes](https://canvas.tue.nl/courses/27578/quizzes) | Week 1 | Week 2| Week 3| Week 4 | Week 5 |  |  | | |
| [Resit quizzes](https://canvas.tue.nl/courses/27578/quizzes)  |   | Week 1 - Resit| Week 2 - Resit | Week 3 - Resit | Week 4 - Resit | Week 5 - Resit |  |   |   |
| Assignment     |         | [Part 1](https://canvas.tue.nl/courses/27578/assignments/123908) | [Part 1](https://canvas.tue.nl/courses/27578/assignments/123908) | [Part 2](https://canvas.tue.nl/courses/27578/assignments/123909) | [Part 2](https://canvas.tue.nl/courses/27578/assignments/123909) | [Part 2](https://canvas.tue.nl/courses/27578/assignments/123909) |  |   |  |
| Final Exam     |    |   | | | | | | | Exam |

: {tbl-colwidths="[19, 9, 9, 9, 9, 9, 9, 9, 9, 9]" .striped .hover} -->

## ✉️ Lecturers & Contact
### Lecturers
:::{#lecturers}
:::

### Teaching Assistants
:::{#teaching-assistants}
:::

_⚠ This course website is carefully filled with all necessary information. When unexpected differences occur between the website and Osiris, the information provided in Osiris is leading._

_⚠ Please note that all educational materials related to this course and uploaded to the course website page, including but not limited to, presentation slides, lecture notes, examination materials, tests, formula sheets, are subject to copyright protection by Eindhoven University of Technology and authors of the course. Additionally, the course materials placed on the website, may contain third parties’ copyright protected material. By copying, distorting, distributing, uploading any of the materials placed on the website to the third party websites, you are responsible and liable for infringing copyright of these resources._



